services:
  front:
    image: mushroom-bet-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
